### ISSUE TITLE
用不了了 依赖的Natasha的版本过低导致type.GetDevelopName()

### ISSUE THREAD

**Issue by hajiuxbz** [night-moon-studio/NCaller#3]
: Could not load type 'Natasha.TypeExtension' from assembly 'Natasha, Version=2.6.1.0, Culture=neutral, PublicKeyToken=null'.

**Comment by NMSAzulX** [comment]
@hajiuxbz 老铁，sorry, 昨天改完没来得及发布, 现在马上发布。 1.6.1 版请查收。

**Comment by hajiuxbz** [comment]
好 辛苦啦

**Comment by NMSAzulX** [comment]
用的舒服吗？ 有问题或者有什么需求尽管提。

**Comment by hajiuxbz** [comment]
舒服，目前用在系统一些关键地方，灵活性大大提升。

**Comment by NMSAzulX** [comment]
哈哈 感谢支持！

**Comment by hajiuxbz** [comment]
应该是我感谢您提供了这么好的库
